services:
  - type: web
    name: cah-server
    env: node
    region: oregon
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cah-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com
      - key: REDIS_URL
        fromService:
          name: cah-redis
          type: redis
          property: connectionString

  - type: web
    name: cah-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend-url.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://your-backend-url.onrender.com

databases:
  - name: cah-db
    databaseName: cards_against_humanity
    ipAllowList: []
    user: cah_user 