services:
  # Backend API Service
  - type: web
    name: cah-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cah-db
          property: connectionString
      - key: CLIENT_URL
        value: https://cah-client.onrender.com

  # Frontend Client Service
  - type: static
    name: cah-client
    buildCommand: cd client && npm install && npm run build
    publishDir: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://cah-server.onrender.com

databases:
  - name: cah-db
    databaseName: cards_against_humanity
    user: cah_admin
    plan: free 